Code pattern mods
IBM-Blockchain-Archive/vehicle-manufacture pull request #54
Opened 2018-08-07 15:36 UTC by ash7594

Modifying the README to follow code pattern guidelines.

2018-08-13 14:49 UTC, awjh-ibm requested changes

2018-08-13 14:49 UTC, awjh-ibm commented on README.md
> +![Architecture Flow](https://github.com/ash7594/vehicle-manufacture/blob/code-pattern-mods/docs/doc-images/arch-flow.png?raw=true)
This should point to the newly added diagram in this repo rather than a link to the fork

2018-08-13 14:49 UTC, awjh-ibm commented on README.md
> +In this code pattern, we will create a vehicle manufacturing program with blockchain using Hyperledger Composer API, and demonstrate it through a Node.js web application. The application showcases th
No need for API Hyperledger Composer is valid

2018-08-13 14:49 UTC, awjh-ibm commented on README.md
> +* Build a Node.js web application to interact with the blockchain network using Composer API
No need for API

2018-08-13 14:56 UTC, awjh-ibm commented on README.md
> +Imagine you are Tesla’s Elon Musk, and have just launched the Model 3 to the public. Hundreds of thousands of car orders are pouring in and you need a way to manage the manufacturing and assembly pro
No entirely sure that this covers the main use case of regulatory body oversight of manufacturers

2018-08-13 18:36 UTC, ash7594 commented on README.md
> +Imagine you are Tesla’s Elon Musk, and have just launched the Model 3 to the public. Hundreds of thousands of car orders are pouring in and you need a way to manage the manufacturing and assembly pro
I see, any suggestions how I could modify this?

2018-08-13 18:37 UTC, ash7594 commented on README.md
> +In this code pattern, we will create a vehicle manufacturing program with blockchain using Hyperledger Composer API, and demonstrate it through a Node.js web application. The application showcases th
Fixed.

2018-08-13 18:37 UTC, ash7594 commented on README.md
> +* Build a Node.js web application to interact with the blockchain network using Composer API
Fixed.

2018-08-13 18:46 UTC, ash7594 commented on README.md
> +![Architecture Flow](https://github.com/ash7594/vehicle-manufacture/blob/code-pattern-mods/docs/doc-images/arch-flow.png?raw=true)
Fixed.

2018-08-14 08:15 UTC, awjh-ibm commented on README.md
> +Imagine you are Tesla’s Elon Musk, and have just launched the Model 3 to the public. Hundreds of thousands of car orders are pouring in and you need a way to manage the manufacturing and assembly pro
I think a brief statement about imagining you are a generic manufacturer who has to conform to certain regulatory standards and thus keep a record of all your business dealings to ensure that you confirm to the regulator's standards and are prepared for audit. Blockchain means that these regulatory rules are embodied by code in a smart contract and thus you can ensure that by recording your dealings using that smart contract in the blockchain you are meeting the requirements laid out and the blockchain provides a full record for audit.

2018-08-16 16:49 UTC, ash7594 commented on README.md
> +Imagine you are Tesla’s Elon Musk, and have just launched the Model 3 to the public. Hundreds of thousands of car orders are pouring in and you need a way to manage the manufacturing and assembly pro
Modified to use the above statements.

2018-08-20 08:13 UTC, awjh-ibm requested changes
Really like the wording and story any chance we could make the reference more generic rather than name dropping Tesla and Musk?

2018-08-20 14:46 UTC, awjh-ibm approved these changes

2018-08-20 14:46 UTC, merged